- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-02582082410591641
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"


#install boto3 and botocore modules to run the above playbook successfully. These modules are required to interact with AWS services using Ansible. You can install them using pip:
#pip install boto3 botocore
#and authenticate to AWS using AWS CLI by running the command aws configure and providing your AWS access key, secret key, region, and output format. This will create a credentials file in your home directory that Ansible will use to authenticate with AWS when running the playbook.
      